window.QUESTION_DATA = [
{
  title: "🎈 Light & Social 🎈",
  items: [
    "{PLAYER}, what small habit of yours would your friends recognize instantly?",
    "{PLAYER}, what is something you do differently when you feel relaxed?",
    "{PLAYER}, what is a harmless thing that always makes your day better?",
    "{PLAYER}, what detail about other people do you notice before most others?",
    "{PLAYER}, what is your personal sign that you’re feeling comfortable somewhere?",
    "{PLAYER}, what everyday moment do you secretly enjoy more than you admit?",
    "{PLAYER}, what is the quickest way someone can make you smile?",
    "{PLAYER}, what kind of silence do you find pleasant rather than awkward?",
    "{PLAYER}, what simple thing do you always appreciate but rarely mention?",
    "{PLAYER}, what small routine makes a place feel familiar to you?",
    "{PLAYER}, what do you usually do when you don’t know anyone in the room?",
    "{PLAYER}, what kind of energy do you bring into a group without trying?",
    "{PLAYER}, what’s something people often misunderstand about you at first?",
    "{PLAYER}, what tiny social gesture do you find surprisingly meaningful?",
    "{PLAYER}, what makes you feel included without anyone saying it out loud?",
    "{PLAYER}, what is a harmless quirk you’ve accepted about yourself?",
    "{PLAYER}, what kind of compliment sticks with you longer than it should?",
    "{PLAYER}, what’s a casual topic you can always talk about with anyone?",
    "{PLAYER}, what do you tend to do with your hands when you’re talking?",
    "{PLAYER}, what makes a conversation feel easy to you?",
    "{PLAYER}, what’s a sound, smell, or detail that instantly relaxes you?",
    "{PLAYER}, what’s something small you always notice when entering a new place?",
    "{PLAYER}, what kind of laugh do you enjoy hearing the most?",
    "{PLAYER}, what’s a social rule you follow even if no one enforces it?",
    "{PLAYER}, what makes you feel welcome in a group setting?",
    "{PLAYER}, what’s a tiny success that always boosts your mood?",
    "{PLAYER}, what do you usually do first when you meet someone new?",
    "{PLAYER}, what part of socializing drains you the least?",
    "{PLAYER}, what’s something people often thank you for?",
    "{PLAYER}, what everyday object do you always keep close without thinking?",
    "{PLAYER}, what kind of moment makes you feel quietly proud?",
    "{PLAYER}, what’s a neutral topic you surprisingly care a lot about?",
    "{PLAYER}, what’s the easiest way for you to break the ice?",
    "{PLAYER}, what makes you stay longer in a place than you planned?",
    "{PLAYER}, what small thing instantly tells you that someone is kind?",
    "{PLAYER}, what do you enjoy more: starting conversations or continuing them?",
    "{PLAYER}, what makes you feel socially “in sync” with others?",
    "{PLAYER}, what’s a simple pleasure you never get tired of?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what’s one thing you always bring to a group dynamic?",
    "{ALL}, what’s a small habit that most people here probably share?"
  ]
},
{
  title: "🧿 Identity & Self-Image 🧿",
  items: [
    "{PLAYER}, what part of your personality do you think people notice first?",
    "{PLAYER}, what part of yourself do you wish people understood better?",
    "{PLAYER}, what label do people often give you that feels incomplete?",
    "{PLAYER}, what version of yourself do you show most often in public?",
    "{PLAYER}, what trait are you quietly proud of?",
    "{PLAYER}, what do you think people get wrong about you at first glance?",
    "{PLAYER}, what part of you only shows up once you feel safe?",
    "{PLAYER}, what’s something you used to hide about yourself that you don’t anymore?",
    "{PLAYER}, what quality do you think makes you memorable to others?",
    "{PLAYER}, what role do you naturally take in a group?",
    "{PLAYER}, what aspect of yourself feels the most consistent over time?",
    "{PLAYER}, what part of your identity changes depending on who you’re with?",
    "{PLAYER}, what strength of yours is also sometimes a weakness?",
    "{PLAYER}, what side of yourself do you rarely get to express?",
    "{PLAYER}, what kind of person do you think you come across as online?",
    "{PLAYER}, what do you think people expect from you once they get to know you?",
    "{PLAYER}, what compliment feels the most accurate when you hear it?",
    "{PLAYER}, what misconception about you takes the longest to correct?",
    "{PLAYER}, what personal value guides your choices more than you admit?",
    "{PLAYER}, what part of your identity feels self-made rather than inherited?",
    "{PLAYER}, what do you feel most confident about right now?",
    "{PLAYER}, what part of yourself are you still figuring out?",
    "{PLAYER}, what quality do you admire in others that you also recognize in yourself?",
    "{PLAYER}, what’s something about you that hasn’t changed in years?",
    "{PLAYER}, what mask do you notice yourself putting on in social situations?",
    "{PLAYER}, what part of you feels strongest when you’re alone?",
    "{PLAYER}, what’s a version of yourself that only close people know?",
    "{PLAYER}, what do you think strangers assume about you?",
    "{PLAYER}, what aspect of yourself do you protect the most?",
    "{PLAYER}, what do you think defines you more: your choices or your reactions?",
    "{PLAYER}, what’s a belief about yourself that you’re slowly unlearning?",
    "{PLAYER}, what role do you feel most comfortable playing in relationships?",
    "{PLAYER}, what part of your identity do you want to grow into?",
    "{PLAYER}, what trait do people rely on you for?",
    "{PLAYER}, what side of yourself do you feel is most authentic?",
    "{PLAYER}, what personal rule do you live by, even if you don’t say it out loud?",
    "{PLAYER}, what part of you feels misunderstood but unchanged?",
    "{PLAYER}, what do you think people remember about you after meeting you?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what identity label fits you best right now, even if it might change?",
    "{ALL}, what’s one thing here that feels true about who you are today?"
  ]
},
{
  title: "🧠 Psychological Triggers 🧠",
  items: [
    "{PLAYER}, what kind of comment stays in your head longer than you’d like?",
    "{PLAYER}, what situation makes you overthink even when you try not to?",
    "{PLAYER}, what tone of voice instantly puts you on edge?",
    "{PLAYER}, what kind of behavior makes you shut down a little?",
    "{PLAYER}, what’s something that bothers you more than you usually admit?",
    "{PLAYER}, what makes you feel quietly judged, even if no one says anything?",
    "{PLAYER}, what kind of silence makes you uncomfortable?",
    "{PLAYER}, what reaction from others makes you second-guess yourself?",
    "{PLAYER}, what’s something small that can ruin your mood faster than it should?",
    "{PLAYER}, what type of attention makes you feel uneasy instead of flattered?",
    "{PLAYER}, what situation makes you feel the need to explain yourself?",
    "{PLAYER}, what kind of misunderstanding affects you the most?",
    "{PLAYER}, what behavior do you tolerate even though it drains you?",
    "{PLAYER}, what makes you feel left out, even in a group?",
    "{PLAYER}, what’s something you’re sensitive about without talking about it much?",
    "{PLAYER}, what kind of pressure do you put on yourself that others might not see?",
    "{PLAYER}, what makes you feel underestimated?",
    "{PLAYER}, what kind of feedback do you struggle to hear, even when it’s fair?",
    "{PLAYER}, what situation makes you feel you have to perform?",
    "{PLAYER}, what small thing makes you feel suddenly insecure?",
    "{PLAYER}, what makes you pull back instead of speaking up?",
    "{PLAYER}, what kind of expectation stresses you out the most?",
    "{PLAYER}, what’s a reaction you have that surprises even you?",
    "{PLAYER}, what makes you feel emotionally tired faster than usual?",
    "{PLAYER}, what’s something you take personally even when it’s not meant that way?",
    "{PLAYER}, what kind of comparison affects you the most?",
    "{PLAYER}, what behavior makes you feel unappreciated?",
    "{PLAYER}, what kind of environment makes you feel on guard?",
    "{PLAYER}, what’s something you wish people were more careful about with you?",
    "{PLAYER}, what situation makes you feel the need to withdraw?",
    "{PLAYER}, what kind of comment makes you replay conversations later?",
    "{PLAYER}, what makes you feel you’re not doing enough?",
    "{PLAYER}, what type of social situation drains you unexpectedly?",
    "{PLAYER}, what’s a trigger you’ve learned to manage better over time?",
    "{PLAYER}, what makes you feel misunderstood without words being exchanged?",
    "{PLAYER}, what kind of interaction makes you feel small?",
    "{PLAYER}, what reaction from others makes you feel validated?",
    "{PLAYER}, what helps you calm down once you feel triggered?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what’s something about your reactions you’re trying to improve?",
    "{ALL}, what’s one thing that tends to trigger people more than they realize?"
  ]
  },
{
  title: "👥 Group Dynamics 👥",
  items: [
    "{PLAYER}, what role do you usually end up playing in a group without planning it?",
    "{PLAYER}, what kind of person do you feel most comfortable being around?",
    "{PLAYER}, what makes a group feel instantly more relaxed to you?",
    "{PLAYER}, what behavior helps groups work better than people realize?",
    "{PLAYER}, what kind of energy do you naturally match in others?",
    "{PLAYER}, what usually breaks the ice for you in a group setting?",
    "{PLAYER}, what makes you feel included without being singled out?",
    "{PLAYER}, what kind of group moment do you enjoy the most?",
    "{PLAYER}, what type of personality balances yours well in a group?",
    "{PLAYER}, what makes group conversations feel natural rather than forced?",
    "{PLAYER}, what kind of silence works in a group and doesn’t feel awkward?",
    "{PLAYER}, what do you appreciate most when people listen in a group?",
    "{PLAYER}, what makes you speak up more than usual in group settings?",
    "{PLAYER}, what makes you step back and observe instead of talking?",
    "{PLAYER}, what’s something groups often do that subtly excludes people?",
    "{PLAYER}, what kind of group behavior makes you feel safe to be yourself?",
    "{PLAYER}, what’s a group dynamic you enjoy but don’t often get?",
    "{PLAYER}, what kind of humor works best in group conversations for you?",
    "{PLAYER}, what makes a group feel unbalanced to you?",
    "{PLAYER}, what do you think you add to a group dynamic?",
    "{PLAYER}, what kind of leadership feels comfortable to you in a group?",
    "{PLAYER}, what makes you trust a group faster?",
    "{PLAYER}, what kind of attention do you enjoy in group settings?",
    "{PLAYER}, what group habit do you find surprisingly important?",
    "{PLAYER}, what makes group energy drop suddenly?",
    "{PLAYER}, what kind of group makes you want to stay longer?",
    "{PLAYER}, what behavior helps quieter people feel included?",
    "{PLAYER}, what do you notice first when a group isn’t working well?",
    "{PLAYER}, what kind of group rule would you introduce if you could?",
    "{PLAYER}, what makes group conversations feel meaningful to you?",
    "{PLAYER}, what role do you avoid playing in groups?",
    "{PLAYER}, what kind of group activity brings people together best?",
    "{PLAYER}, what makes group tension easier to release?",
    "{PLAYER}, what’s something people underestimate about group comfort?",
    "{PLAYER}, what makes you feel respected in a group?",
    "{PLAYER}, what kind of group dynamic drains you the least?",
    "{PLAYER}, what’s a small thing a group can do to feel more connected?",
    "{PLAYER}, what makes a group feel emotionally safe?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what do you think groups need more of to work better?",
    "{ALL}, what’s one group habit that makes any gathering better?"
  ]
},
{
  title: "💞 Connection & Intimacy 💞",
  items: [
    "{PLAYER}, what makes you feel emotionally close to someone?",
    "{PLAYER}, what kind of conversation makes you feel truly heard?",
    "{PLAYER}, what small gesture makes you feel cared for?",
    "{PLAYER}, what helps you open up to people over time?",
    "{PLAYER}, what kind of attention makes you feel safe?",
    "{PLAYER}, what makes you trust someone more quickly?",
    "{PLAYER}, what do you need from others to feel comfortable sharing?",
    "{PLAYER}, what kind of moment makes you feel connected without words?",
    "{PLAYER}, what helps you relax around someone new?",
    "{PLAYER}, what makes you feel emotionally supported?",
    "{PLAYER}, what kind of presence do you find comforting?",
    "{PLAYER}, what makes you feel seen rather than observed?",
    "{PLAYER}, what helps you stay open instead of guarded?",
    "{PLAYER}, what kind of question makes you want to answer honestly?",
    "{PLAYER}, what makes a shared silence feel intimate rather than awkward?",
    "{PLAYER}, what kind of listening makes the biggest difference to you?",
    "{PLAYER}, what makes you feel emotionally safe in a group?",
    "{PLAYER}, what helps you feel accepted as you are?",
    "{PLAYER}, what kind of reassurance do you value most?",
    "{PLAYER}, what makes you feel closer to someone over time?",
    "{PLAYER}, what kind of emotional effort do you appreciate from others?",
    "{PLAYER}, what makes vulnerability feel worth it to you?",
    "{PLAYER}, what kind of response helps you open up more?",
    "{PLAYER}, what helps you feel understood without explaining everything?",
    "{PLAYER}, what kind of emotional connection do you crave the most?",
    "{PLAYER}, what makes you feel comfortable being yourself?",
    "{PLAYER}, what kind of support feels natural rather than forced?",
    "{PLAYER}, what helps you feel grounded when connecting with others?",
    "{PLAYER}, what kind of presence makes you feel calm?",
    "{PLAYER}, what makes you feel emotionally aligned with someone?",
    "{PLAYER}, what kind of honesty feels gentle to you?",
    "{PLAYER}, what helps you feel close without feeling exposed?",
    "{PLAYER}, what kind of emotional space do you need to open up?",
    "{PLAYER}, what makes you feel respected in intimate conversations?",
    "{PLAYER}, what kind of connection feels most natural to you?",
    "{PLAYER}, what helps emotional closeness grow slowly?",
    "{PLAYER}, what makes you want to stay emotionally present?",
    "{PLAYER}, what kind of emotional warmth do you notice most?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what helps you feel connected even in quiet moments?",
    "{ALL}, what’s one thing that helps people feel closer to each other?"
  ]
},
{
  title: "✨ Flirt & Tension ✨",
  items: [
    "{PLAYER}, what kind of attention makes you feel noticed in a good way?",
    "{PLAYER}, what small signal tells you someone is interested?",
    "{PLAYER}, what kind of compliment feels subtle but powerful to you?",
    "{PLAYER}, what makes a conversation suddenly feel charged?",
    "{PLAYER}, what kind of eye contact do you find intriguing?",
    "{PLAYER}, what’s a harmless way you show interest without saying it directly?",
    "{PLAYER}, what makes playful teasing enjoyable rather than awkward?",
    "{PLAYER}, what kind of pause in conversation feels meaningful?",
    "{PLAYER}, what makes you lean in—emotionally or physically—during a chat?",
    "{PLAYER}, what kind of curiosity from someone feels flattering?",
    "{PLAYER}, what tone of voice makes you pay more attention?",
    "{PLAYER}, what’s a small gesture that can change the vibe instantly?",
    "{PLAYER}, what kind of smile makes you wonder what’s behind it?",
    "{PLAYER}, what makes you feel a spark without anything explicit happening?",
    "{PLAYER}, what kind of closeness feels exciting but still safe?",
    "{PLAYER}, what’s a subtle way someone has caught your attention before?",
    "{PLAYER}, what kind of playful challenge do you enjoy in flirting?",
    "{PLAYER}, what makes tension fun instead of stressful?",
    "{PLAYER}, what kind of interaction makes you feel pleasantly nervous?",
    "{PLAYER}, what detail about someone makes you curious to know more?",
    "{PLAYER}, what kind of back-and-forth feels like chemistry to you?",
    "{PLAYER}, what makes a compliment feel personal rather than generic?",
    "{PLAYER}, what kind of shared moment feels intimate even if brief?",
    "{PLAYER}, what makes you want a conversation to continue?",
    "{PLAYER}, what kind of mystery do you find attractive?",
    "{PLAYER}, what makes flirting feel natural rather than forced?",
    "{PLAYER}, what kind of attention makes you blush internally?",
    "{PLAYER}, what’s a small risk you enjoy taking when flirting?",
    "{PLAYER}, what makes you feel chosen in a subtle way?",
    "{PLAYER}, what kind of energy exchange feels exciting to you?",
    "{PLAYER}, what makes tension slowly build rather than fade?",
    "{PLAYER}, what kind of humor works best when flirting?",
    "{PLAYER}, what makes you feel there’s something unspoken in the air?",
    "{PLAYER}, what kind of interaction leaves you thinking about it later?",
    "{PLAYER}, what makes you feel both relaxed and alert at the same time?",
    "{PLAYER}, what kind of attention makes you feel special without pressure?",
    "{PLAYER}, what makes flirting feel playful instead of serious?",
    "{PLAYER}, what kind of closeness do you enjoy before anything physical?",
    "{PLAYER}, what’s a sign that tension is mutual?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{ALL}, what’s one subtle thing that can make a vibe feel flirty?"
  ]
},
{
  title: "🔥 Erotic – Soft Level 🔥",
  items: [
    "{PLAYER}, what kind of closeness makes your attention sharpen instantly?",
    "{PLAYER}, what small detail about someone can feel unexpectedly attractive?",
    "{PLAYER}, what kind of touch feels intimate even if it’s brief?",
    "{PLAYER}, what makes a moment feel charged without anything happening?",
    "{PLAYER}, what kind of eye contact lingers a little too long?",
    "{PLAYER}, what kind of compliment feels almost too personal to ignore?",
    "{PLAYER}, what makes anticipation more exciting than action?",
    "{PLAYER}, what kind of presence makes you more aware of your body?",
    "{PLAYER}, what kind of silence feels thick rather than empty?",
    "{PLAYER}, what makes you feel subtly desired?",
    "{PLAYER}, what kind of proximity makes you notice your breathing?",
    "{PLAYER}, what kind of attention makes you feel warm rather than nervous?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what detail about someone’s voice can feel intimate?",
    "{PLAYER}, what kind of slow moment makes everything else fade out?",
    "{PLAYER}, what makes you feel a spark without understanding why?",
    "{PLAYER}, what kind of shared look feels private even in a group?",
    "{PLAYER}, what kind of closeness feels exciting but still safe?",
    "{PLAYER}, what makes tension build rather than break?",
    "{PLAYER}, what kind of timing makes a moment feel intentional?",
    "{PLAYER}, what kind of curiosity feels flattering instead of intrusive?",
    "{PLAYER}, what kind of attention makes you more aware of yourself?",
    "{PLAYER}, what makes a moment feel sensual without being sexual?",
    "{PLAYER}, what kind of slow interaction do you enjoy the most?",
    "{PLAYER}, what makes you want to stay present in a charged moment?",
    "{PLAYER}, what kind of atmosphere makes desire feel subtle?",
    "{PLAYER}, what kind of closeness feels natural rather than rushed?",
    "{PLAYER}, what detail makes a person feel magnetic to you?",
    "{PLAYER}, what kind of tension do you enjoy sitting with?",
    "{PLAYER}, what makes a shared moment feel intimate even without words?",
    "{PLAYER}, what kind of pause makes you want more?",
    "{PLAYER}, what makes you feel quietly wanted?",
    "{PLAYER}, what kind of attention feels deliberate rather than accidental?",
    "{PLAYER}, what makes desire feel playful instead of heavy?",
    "{PLAYER}, what kind of moment makes you hyper-aware of the present?",
    "{PLAYER}, what kind of energy exchange feels electric but controlled?",
    "{PLAYER}, what makes you enjoy the build-up more than the outcome?",
    "{PLAYER}, what kind of closeness makes time feel slower?",
    "{PLAYER}, what makes a moment feel softly erotic?",
    "{PLAYER}, what kind of tension do you hope doesn’t resolve too quickly?",
    "{ALL}, what’s one thing that can make a moment feel subtly erotic?"
  ]
},
 {
    title: "⚡ QuickPick ⚡",
    items: [
      "{PLAYER}: Sweet or salty?",
      "{PLAYER}: Morning or night?",
      "{PLAYER}: Beach or mountains?",
      "{PLAYER}: Coffee or tea?",
      "{PLAYER}: Hot or cold shower?",
      "{PLAYER}: Hug or handshake?",
      "{PLAYER}: Texting or calling?",
      "{PLAYER}: Dogs or cats?",
      "{PLAYER}: Introvert or extrovert?",
      "{PLAYER}: Book or movie?",
      "{PLAYER}: Sneakers or barefoot?",
      "{PLAYER}: Smile or eyes first?",
      "{PLAYER}: Loud laugh or shy smile?",
      "{PLAYER}: Sweet talk or teasing?",
      "{PLAYER}: Compliment or joke?",
      "{PLAYER}: Slow build or fast spark?",
      "{PLAYER}: Curious or shy?",
      "{PLAYER}: First notice: voice or body?",
      "{PLAYER}: Long chat or short glance?",
      "{PLAYER}: Being admired or understood?",
      "{PLAYER}: Words or body language?",
      "{PLAYER}: Playful or serious?",
      "{PLAYER}: Eye contact or touch?",
      "{PLAYER}: Whisper or stare?",
      "{PLAYER}: Hold close or stay apart?",
      "{PLAYER}: Watch or be watched?",
      "{PLAYER}: Tease or be teased?",
      "{PLAYER}: Rough or slow?",
      "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
      "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
      "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
      "{PLAYER}: Lights on or lights off?",
      "{PLAYER}: Moan or whisper?",
      "{PLAYER}: Control or surrender?",
      "{PLAYER}: Kiss or bite?",
      "{PLAYER}: Top or bottom?",
      "{PLAYER}: Touch or talk?",
      "{PLAYER}: Alone or with audience?",
      "{PLAYER}: Naked truth or sexy lie?",
      "{PLAYER}: Public fantasy or private secret?",
      "{PLAYER}: Trust or lust?",
      "{PLAYER}: Laugh or blush?",
      "{PLAYER}: Eyes open or closed?",
      "{PLAYER}: Silent desire or loud passion?",
      "{PLAYER}: Sauna or shower?",
      "{PLAYER}: Sun on skin or breeze on skin?",
      "{PLAYER}: Swim nude or sunbathe nude?",
      "{PLAYER}: Daylight nude or night nude?",
      "{PLAYER}: First nude step: fast or slow?",
      "{PLAYER}: Beach or forest nudity?",
      "{PLAYER}: Necklace or nothing?",
      "{PLAYER}: Sweet or spicy nude moment?",
      "{PLAYER}: Pizza or pasta?",
      "{PLAYER}: Wine or beer?",
      "{PLAYER}: Europe or America trip?",
      "{PLAYER}: Train or plane?",
      "{PLAYER}: Early dinner or late dinner?",
      "{PLAYER}: Learn slang or learn food?",
      "{PLAYER}: Tradition or modern?",
      "{PLAYER}: Share or keep secret?"
    ]
  },
{
  title: "🌙 Deep & Intimate 🌙",
  items: [
    "{PLAYER}, what makes you feel truly safe opening up to someone?",
    "{PLAYER}, what part of yourself do you only reveal when trust is earned?",
    "{PLAYER}, what kind of emotional closeness do you find most powerful?",
    "{PLAYER}, what makes you feel deeply understood?",
    "{PLAYER}, what do you need most when you’re emotionally vulnerable?",
    "{PLAYER}, what kind of presence makes you feel less alone?",
    "{PLAYER}, what does emotional intimacy mean to you personally?",
    "{PLAYER}, what makes you feel comfortable sharing difficult thoughts?",
    "{PLAYER}, what kind of connection feels rare but meaningful to you?",
    "{PLAYER}, what helps you stay open even when it feels risky?",
    "{PLAYER}, what emotional boundary is most important for you?",
    "{PLAYER}, what makes you feel accepted without having to explain yourself?",
    "{PLAYER}, what kind of honesty feels gentle rather than overwhelming?",
    "{PLAYER}, what makes emotional closeness feel natural instead of forced?",
    "{PLAYER}, what part of emotional intimacy scares you the most?",
    "{PLAYER}, what makes you feel seen beyond appearances?",
    "{PLAYER}, what kind of silence feels intimate to you?",
    "{PLAYER}, what helps you trust someone with your feelings?",
    "{PLAYER}, what emotional need do you often put last?",
    "{PLAYER}, what makes you feel emotionally held?",
    "{PLAYER}, what kind of reassurance calms you the most?",
    "{PLAYER}, what makes emotional vulnerability worth the risk?",
    "{PLAYER}, what kind of connection makes time feel irrelevant?",
    "{PLAYER}, what do you need to feel emotionally close to someone?",
    "{PLAYER}, what part of yourself are you still learning to share?",
    "{PLAYER}, what makes you feel emotionally grounded with others?",
    "{PLAYER}, what kind of emotional support feels most genuine?",
    "{PLAYER}, what makes you retreat emotionally?",
    "{PLAYER}, what helps you stay present during deep conversations?",
    "{PLAYER}, what kind of closeness makes you feel calm?",
    "{PLAYER}, what makes emotional intimacy grow slowly but steadily?",
    "{PLAYER}, what kind of question opens you up the most?",
    "{PLAYER}, what makes you feel emotionally aligned with someone?",
    "{PLAYER}, what kind of emotional effort do you notice immediately?",
    "{PLAYER}, what makes you feel safe enough to be fully yourself?",
    "{PLAYER}, what kind of emotional connection do you crave but rarely say out loud?",
    "{PLAYER}, what helps you feel emotionally balanced in close relationships?",
    "{PLAYER}, what makes emotional honesty easier for you?",
    "{PLAYER}, what kind of presence feels like home to you?",
    "{ALL}, what’s one thing that deepens emotional intimacy between people?"
  ]
},
{
  "title": "❌ Never have I Ever ✔",
  "items": [
    "{ALL}: Never have I ever had a crush on a straight guy.",
    "{ALL}: Never have I ever flirted with someone just to get something I wanted.",
    "{ALL}: Never have I ever fallen for a friend.",
    "{ALL}: Never have I ever kissed someone I wasn’t supposed to.",
    "{ALL}: Never have I ever sent a message I instantly regretted.",
    "{ALL}: Never have I ever checked an ex’s profile more than once a week.",
    "{ALL}: Never have I ever been in love with someone who didn’t love me back.",
    "{ALL}: Never have I ever stayed friends with someone just because I was still attracted to them.",
    "{ALL}: Never have I ever been turned on by someone’s voice.",
    "{ALL}: Never have I ever imagined a coworker naked.",
    "{ALL}: Never have I ever gone on a date just because I was bored.",
    "{ALL}: Never have I ever been caught in a lie during a hookup.",
    "{ALL}: Never have I ever kissed more than one person in the same night.",
    "{ALL}: Never have I ever been on a date that ended up somewhere unexpected.",
    "{ALL}: Never have I ever been told I was someone’s fantasy.",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{ALL}: Never have I ever ghosted someone who didn’t deserve it.",
    "{ALL}: Never have I ever wanted to kiss someone while pretending I didn’t.",
    "{ALL}: Never have I ever been surprised by who I found attractive.",
    "{ALL}: Never have I ever had a dream about someone in this room.",
    "{ALL}: Never have I ever hooked up with someone I met online.",
    "{ALL}: Never have I ever flirted with a friend’s ex.",
    "{ALL}: Never have I ever lied about my relationship status.",
    "{ALL}: Never have I ever woken up next to someone whose name I didn’t remember.",
    "{ALL}: Never have I ever said I’d call and never did.",
    "{ALL}: Never have I ever felt jealous watching two people flirt.",
    "{ALL}: Never have I ever felt something real during a one-night connection.",
    "{ALL}: Never have I ever been kissed by someone I wasn’t expecting.",
    "{ALL}: Never have I ever kept a secret crush for longer than a year.",
    "{ALL}: Never have I ever been curious about someone older than me.",
    "{ALL}: Never have I ever gone home with someone I just met.",
    "{ALL}: Never have I ever met someone who completely changed how I see attraction.",
    "{ALL}: Never have I ever been the one to make the first move.",
    "{ALL}: Never have I ever lied to make myself sound more interesting.",
    "{ALL}: Never have I ever texted someone just because I was lonely.",
    "{ALL}: Never have I ever re-read old conversations just to feel something again.",
    "{ALL}: Never have I ever shared a bed with a friend just for comfort.",
    "{ALL}: Never have I ever been mistaken for being in a relationship with a friend.",
    "{ALL}: Never have I ever thought of someone during a moment of silence.",
    "{ALL}: Never have I ever made eye contact that lasted longer than it should have.",
    "{ALL}: Never have I ever felt an instant connection with a stranger.",
    "{ALL}: Never have I ever been on a date that turned into a story worth telling.",
    "{ALL}: Never have I ever flirted with someone who was clearly out of my league.",
    "{ALL}: Never have I ever been invited to a party that changed my night completely.",
    "{ALL}: Never have I ever been attracted to someone who looked nothing like my type.",
    "{ALL}: Never have I ever stayed up all night talking to someone new.",
    "{ALL}: Never have I ever been part of a moment that felt cinematic.",
    "{ALL}: Never have I ever said something bold just to see someone’s reaction.",
    "{ALL}: Never have I ever gone along with a situation I didn’t plan for.",
    "{ALL}: Never have I ever had a moment of chemistry I couldn’t explain.",
    "{ALL}: Never have I ever been surprised by my own curiosity.",
    "{ALL}: Never have I ever met someone who made me question what I thought I wanted.",
    "{ALL}: Never have I ever thought about someone in this group at a random time of day.",
    "{ALL}: Never have I ever done something spontaneous and unforgettable.",
    "{ALL}: Never have I ever laughed in the middle of a moment that was supposed to be serious.",
    "{ALL}: Never have I ever shared a secret that wasn’t mine to share.",
    "{ALL}: Never have I ever been the reason someone blushed.",
    "{ALL}: Never have I ever been caught staring at someone longer than I should have.",
    "{ALL}: Never have I ever had a moment I wished could happen again."
  ]
},
	{
  "title": "❌ Never have I Ever - SPICY 🌶",
  "items": [
  "{ALL}: Never have I ever made out with someone in a pool.",
  "{ALL}: Never have I ever had reconciliation sex.",
  "{ALL}: Never have I ever masturbated in the shower.",
  "{ALL}: Never have I ever asked my ex to be friends with benefits.",
  "{ALL}: Never have I ever kissed anyone's feet.",
  "{ALL}: Never have I ever secretly masturbated in someone else's house.",
  "{ALL}: Never have I ever done a quickie.",
  "{ALL}: Never have I ever given love bites to my partner.",
  "{ALL}: Never have I ever had sex with someone just because you were desperate to have it.",
  "{ALL}: Never have I ever been rejected when I wanted to do it with my partner.",
  "{ALL}: Never have I ever dumped someone because of bad sex.",
  "{ALL}: Never have I ever watched porn with a partner.",
  "{ALL}: Never have I ever watched a TV series just for the steamy scenes.",
  "{ALL}: Never have I ever given someone a fake phone number.",
  "{ALL}: Never have I ever disliked being kissed on the neck.",
  "{ALL}: Never have I ever gone an entire week without masturbating.",
  "{ALL}: Never have I ever slept with my ex.",
  "{ALL}: Never have I ever had a secret relationship.",
  "{ALL}: Never have I ever passed out after having sex.",
  "{ALL}: Never have I ever removed porn videos from my laptop for fear of someone finding them.",
  "{ALL}: Never have I ever asked my partner to shave his pubic hair.",
  "{ALL}: Never have I ever faked having an orgasm.",
  "{ALL}: Never have I ever had a crush on a celebrity.",
  "{ALL}: Never have I ever went into a sex shop and bought something.",
  "{ALL}: Never have I ever flirted with my college professor.",
  "{ALL}: Never have I ever gone to a booty call.",
  "{ALL}: Never have I ever had a friend in bed.",
  "{ALL}: Never have I ever owned a porn magazine.",
  "{ALL}: Never have I ever forgot who I had sex with the night before because of a hangover.",
  "{ALL}: Never have I ever had sex with anyone more than five years younger than me.",
  "{ALL}: Never have I ever gave lingerie to someone I dated.",
  "{ALL}: Never have I ever had sex with a virgin.",
  "{ALL}: Never have I ever received a hickey.",
  "{ALL}: Never have I ever had sex with more than one person within 24 hours.",
  "{ALL}: Never have I ever streaked naked.",
  "{ALL}: Never have I ever had an injury in the bedroom.",
  "{ALL}: Never have I ever searched for porn online using public WiFi.",
  "{ALL}: Never have I ever shown your private parts to a stranger for fun.",
  "{ALL}: Never have I ever had sex standing up.",
  "{ALL}: Never have I ever dehydrated after having sex.",
  "{ALL}: Never have I ever had a wet dream.",
  "{ALL}: Never have I ever read sex stories online.",
  "{ALL}: Never have I ever flirted with someone ten years older.",
  "{ALL}: Never have I ever had a fling with someone five years older.",
  "{ALL}: Never have I ever explored hot videos online.",
  "{ALL}: Never have I ever had sex in the bed of a pickup truck.",
  "{ALL}: Never have I ever joined the mile high club.",
  "{ALL}: Never have I ever had a handjob in the car.",
  "{ALL}: Never have I ever had sex in the morning.",
  "{ALL}: Never have I ever had sex in a hotel abroad.",
  "{ALL}: Never have I ever had a make out session in a jacuzzi.",
  "{ALL}: Never have I ever had sex on a moving train.",
  "{ALL}: Never have I ever had sex in a public place.",
  "{ALL}: Never have I ever had sex in a bathroom.",
  "{ALL}: Never have I ever had sex in an elevator.",
  "{ALL}: Never have I ever had sex in front of anyone.",
  "{ALL}: Never have I ever had sex in my parents' bed.",
  "{ALL}: Never have I ever had sex on a bus.",
  "{ALL}: Never have I ever had sex in a tent.",
  "{ALL}: Never have I ever had sex on a beach.",
  "{ALL}: Never have I ever had sex under the influence of substances.",
  "{ALL}: Never have I ever had sex in a sleeping bag.",
  "{ALL}: Never have I ever had sex in the shower.",
  "{ALL}: Never have I ever woken up your roommate due to noise during sex.",
  "{ALL}: Never have I ever woken up without remembering anything from the night before.",
  "{ALL}: Never have I ever had sex with someone who spoke another language.",
  "{ALL}: Never have I ever had sex with the same person two days in a row.",
  "{ALL}: Never have I ever hurt myself with sex toys.",
  "{ALL}: Never have I ever been irritable after sex.",
  "{ALL}: Never have I ever received a sensual massage.",
  "{ALL}: Never have I ever been too tired to have sex.",
  "{ALL}: Never have I ever farted during sex.",
  "{ALL}: Never have I ever angry with my partner for an unsatisfactory performance.",
  "{ALL}: Never have I ever cheated in a relationship.",
  "{ALL}: Never have I ever used a sex toy.",
  "{ALL}: Never have I ever had a pregnancy scare.",
  "{ALL}: Never have I ever stopped sex and walked away.",
  "{ALL}: Never have I ever made a porn video.",
  "{ALL}: Never have I ever spied on anyone taking a shower.",
  "{ALL}: Never have I ever used lubricant during masturbation.",
  "{ALL}: Never have I ever got a lap dance.",
  "{ALL}: Never have I ever tried sexual positions found online.",
  "{ALL}: Never have I ever seen anyone from my family masturbate.",
  "{ALL}: Never have I ever whispered sensually in someone's ear.",
  "{ALL}: Never have I ever had trouble walking the day after sex.",
  "{ALL}: Never have I ever shave another person's body hair.",
  "{ALL}: Never have I ever showered with anyone else.",
  "{ALL}: Never have I ever slept with someone just out of physical attraction.",
  "{ALL}: Never have I ever licked someone's feet.",
  "{ALL}: Never have I ever waxed your private parts.",
  "{ALL}: Never have I ever sexted to turn someone on.",
  "{ALL}: Never have I ever tried phone sex.",
  "{ALL}: Never have I ever had sex with someone who had erection problems.",
  "{ALL}: Never have I ever used a household object as a sex toy.",
  "{ALL}: Never have I ever played with ice cubes privately.",
  "{ALL}: Never have I ever wanted to work in a strip club.",
  "{ALL}: Never have I ever had a crush on a fictional character.",
  "{ALL}: Never have I ever been stuck outside the house naked.",
  "{ALL}: Never have I ever bought lingerie for someone.",
  "{ALL}: Never have I ever brought a sex toy through airport security.",
  "{ALL}: Never have I ever caught my partner with another person.",
  "{ALL}: Never have I ever fallen asleep during sex.",
  "{ALL}: Never have I ever been mistaken for a sex worker.",
  "{ALL}: Never have I ever gave a ride to a stranger while alone on the highway.",
  "{ALL}: Never have I ever taken a bath with anyone else.",
  "{ALL}: Never have I ever given my partner a sexy nickname.",
  "{ALL}: Never have I ever imagined working in a brothel.",
  "{ALL}: Never have I ever seen someone naked by accident.",
  "{ALL}: Never have I ever hand pleasured someone in public.",
  "{ALL}: Never have I ever tried to make a silent fart that turned out to be loud.",
  "{ALL}: Never have I ever watched an adult film with my partner.",
  "{ALL}: Never have I ever done something naughty that made me blush.",
  "{ALL}: Never have I ever performed a provocative dance in front of anyone.",
  "{ALL}: Never have I ever done something stupid and justified it with “You only live once”.",
  "{ALL}: Never have I ever sent a spicy message to the wrong person.",
  "{ALL}: Never have I ever French kissed a stranger in a bar.",
  "{ALL}: Never have I ever had sex more than twice in one day.",
  "{ALL}: Never have I ever thought about having plastic surgery.",
  "{ALL}: Never have I ever tried fisting.",
  "{ALL}: Never have I ever had sex at a wedding.",
  "{ALL}: Never have I ever role-played during sex.",
  "{ALL}: Never have I ever had oral sex with someone you just met.",
  "{ALL}: Never have I ever smelled someone's used underwear.",
  "{ALL}: Never have I ever had a finger up your butt.",
  "{ALL}: Never have I ever tasted sperm.",
  "{ALL}: Never have I ever lost anything in one of my holes.",
  "{ALL}: Never have I ever taken Viagra.",
  "{ALL}: Never have I ever had more than ten sexual partners.",
  "{ALL}: Never have I ever had sexual thoughts when seeing a wedgie in public.",
  "{ALL}: Never have I ever stuck my penis in a vacuum cleaner.",
  "{ALL}: Never have I ever dressed like a provocative schoolgirl.",
  "{ALL}: Never have I ever made hot videos. (If yes, are they in this server?)",
  "{ALL}: Never have I ever received a handjob.",
  "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
  "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
  "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
  "{ALL}: Never have I ever tried more than three sexual positions in one session.",
  "{ALL}: Never have I ever taken a sexy selfie.",
  "{ALL}: Never have I ever paid attention to the plot of a porn film.",
  "{ALL}: Never have I ever used edible underwear.",
  "{ALL}: Never have I ever participated in a double penetration.",
  "{ALL}: Never have I ever visited a pick up party.",
  "{ALL}: Never have I ever searched for someone (in this game session) photo and videos in this server.",
  "{ALL}: Never have I ever looked for someone's nude photos online.",
  "{ALL}: Never have I ever spoke spicy to my partner.",
  "{ALL}: Never have I ever had sperm in my hair or beard.",
  "{ALL}: Never have I ever went to a spa and had sex.",
  "{ALL}: Never have I ever driven a car naked or with minimal clothing.",
  "{ALL}: Never have I ever had sex while a family member was home.",
  "{ALL}: Never have I ever performed a striptease for anyone.",
  "{ALL}: Never have I ever gone to a sex shop with the person I'm dating.",
  "{ALL}: Never have I ever visited a stripper club.",
  "{ALL}: Never have I ever played strip poker for a bet.",
  "{ALL}: Never have I ever had sperm in my eye.",
  "{ALL}: Never have I ever had sex with the window open.",
  "{ALL}: Never have I ever heard anyone else do it.",
  "{ALL}: Never have I ever picked up someone you met on a dating app.",
  "{ALL}: Never have I ever licked whipped cream off someone's naked body.",
  "{ALL}: Never have I ever played footsie under a table in public.",
  "{ALL}: Never have I ever ripped someone's clothes while kissing.",
  "{ALL}: Never have I ever touched someone's pants from under the table.",
  "{ALL}: Never have I ever shot a private sex video of other people.",
  "{ALL}: Never have I ever put my hands in my pants to warm up.",
  "{ALL}: Never have I ever worn jock straps.",
  "{ALL}: Never have I ever pulled any mischief in an elevator.",
  "{ALL}: Never have I ever sexted with someone I didn't know on a bet.",
  "{ALL}: Never have I ever used toys during sex.",
  "{ALL}: Never have I ever made a hot video about a bet.",
  "{ALL}: Never have I ever swallowed.",
  "{ALL}: Never have I ever tried a flavored condom.",
  "{ALL}: Never have I ever written an erotic story.",
  "{ALL}: Never have I ever used a random object to masturbate.",
  "{ALL}: Never have I ever worn my partner's underwear to work.",
  "{ALL}: Never have I ever purchased sex toys.",
  "{ALL}: Never have I ever adjusted my buttons based on who is in the room.",
  "{ALL}: Never have I ever been tied up.",
  "{ALL}: Never have I ever dated two people at the same time.",
  "{ALL}: Never have I ever fantasized about having sex with my partner's brother or sister.",
  "{ALL}: Never have I ever lied about my virginity.",
  "{ALL}: Never have I ever had sex with someone to get a promotion at work.",
  "{ALL}: Never have I ever flirted with someone who was busy.",
  "{ALL}: Never have I ever licked a foot.",
  "{ALL}: Never have I ever worn handcuffs.",
  "{ALL}: Never have I ever slept with a friend's ex-partner.",
  "{ALL}: Never have I ever had to go to hospital due to a sexual accident.",
  "{ALL}: Never have I ever said 'I love you' without meaning it.",
  "{ALL}: Never have I ever screamed during sex trying to keep the noise down.",
  "{ALL}: Never have I ever kissed someone else while my partner was in the other room.",
  "{ALL}: Never have I ever had sex with anyone more than twice my age."
 ]
},
{
  title: "🔥 Erotic – Medium Level 🔥",
  items: [
    "{PLAYER}, what kind of touch instantly changes the mood for you?",
    "{PLAYER}, what kind of kiss do you find the most exciting?",
    "{PLAYER}, what part of your body do you enjoy having attention on the most?",
    "{PLAYER}, what kind of pace do you prefer when desire is building?",
    "{PLAYER}, what makes you feel wanted rather than just desired?",
    "{PLAYER}, what kind of verbal attention turns you on the most?",
    "{PLAYER}, what kind of teasing do you enjoy receiving?",
    "{PLAYER}, what kind of situation makes you feel more open to desire?",
    "{PLAYER}, what makes a sexual moment feel intimate instead of mechanical?",
    "{PLAYER}, what kind of anticipation excites you more than action?",
    "{PLAYER}, what kind of dynamic do you enjoy more: leading or following?",
    "{PLAYER}, what makes you feel confident in intimate situations?",
    "{PLAYER}, what kind of attention helps you relax into pleasure?",
    "{PLAYER}, what kind of environment heightens your arousal?",
    "{PLAYER}, what kind of fantasy feels exciting but still realistic?",
    "{PLAYER}, what kind of closeness do you crave before things get physical?",
    "{PLAYER}, what makes you feel most in tune with a partner’s desire?",
    "{PLAYER}, what kind of communication makes sex better for you?",
    "{PLAYER}, what kind of intimacy do you enjoy outside of penetration?",
    "{PLAYER}, what makes you feel comfortable expressing what you want?",
    "{PLAYER}, what kind of physical connection makes you feel grounded?",
    "{PLAYER}, what kind of slow moment turns you on unexpectedly?",
    "{PLAYER}, what kind of attention do you enjoy giving the most?",
    "{PLAYER}, what makes you feel sexually confident?",
    "{PLAYER}, what kind of sensual activity do you enjoy that isn’t obviously sexual?",
    "{PLAYER}, what kind of tension do you like to stretch out?",
    "{PLAYER}, what makes a sexual moment feel playful to you?",
    "{PLAYER}, what kind of reassurance do you need to fully let go?",
    "{PLAYER}, what part of intimacy do you value more as you get older?",
    "{PLAYER}, what kind of fantasy feels more about connection than sex?",
    "{PLAYER}, what kind of touch feels more intimate than expected?",
    "{PLAYER}, what makes you feel free to explore desire safely?",
    "{PLAYER}, what kind of sexual curiosity do you enjoy indulging?",
    "{PLAYER}, what makes you feel most present during intimate moments?",
    "{PLAYER}, what kind of vulnerability makes desire stronger for you?",
    "{PLAYER}, what kind of erotic energy do you enjoy sharing?",
    "{PLAYER}, what kind of boundary actually makes desire grow?",
    "{PLAYER}, what kind of intimacy feels the most satisfying to you?",
    "{PLAYER}, what makes a sexual connection feel memorable?",
    "{ALL}, what’s one thing that makes desire feel more intense but still safe?"
  ]
},
{
  title: "🔞 Erotic – Intimate & Raw 🔞",
  items: [
    "{PLAYER}, what physical detail on a man instantly grabs your attention, even before he speaks?",
    "{PLAYER}, what body feature do you secretly hope people notice about you first?",
    "{PLAYER}, what compliment about your body hits you the hardest in a good way?",
    "{PLAYER}, what’s your favorite kind of body contact when you’re close with someone?",
    "{PLAYER}, what’s a body-related insecurity you’ve learned to handle better over time?",
    "{PLAYER}, what’s a specific kind of touch you love, but only when trust is there?",
    "{PLAYER}, what’s something about men’s bodies you find oddly hypnotic?",
    "{PLAYER}, what’s your biggest “yes” when it comes to chemistry—something that flips the switch fast?",
    "{PLAYER}, what’s your biggest “no”—the thing that kills the vibe instantly?",
    "{PLAYER}, what’s a preference you have that you used to feel shy admitting?",
    "{PLAYER}, what’s a preference you discovered late and went, “oh… that explains a lot”?",
    "{PLAYER}, what kind of confidence in a guy is genuinely irresistible to you?",
    "{PLAYER}, what kind of confidence is a turn-off because it feels fake?",
    "{PLAYER}, what’s a sexual disappointment you’ve had that taught you something useful?",
    "{PLAYER}, what’s the most awkward intimate moment you’ve had that’s funny now?",
    "{PLAYER}, what’s a small “incident” in bed that could’ve ruined it but somehow made it better?",
    "{PLAYER}, what’s a moment where your body betrayed you at the worst time (nerves, timing, stamina, etc.)?",
    "{PLAYER}, what’s the funniest thing you or someone else said in the middle of a hot moment?",
    "{PLAYER}, what’s the most unexpected thing that has turned you on in the past?",
    "{PLAYER}, what’s an unexpected thing that turned you off even though you wanted it to work?",
    "{PLAYER}, what’s the most satisfying “conquest” you’ve had—not because of looks, but because it felt earned?",
    "{PLAYER}, what’s the most memorable compliment you received after sex?",
    "{PLAYER}, what’s a private “green flag” in bed that makes you relax instantly?",
    "{PLAYER}, what’s a private “red flag” in bed that makes you mentally check out?",
    "{PLAYER}, what’s something you wish more guys understood about male-on-male intimacy?",
    "{PLAYER}, what’s a boundary you set now that you didn’t set when you were younger?",
    "{PLAYER}, what’s a fantasy you like because of the dynamic, not the explicit details?",
    "{PLAYER}, what’s a sexual skill you’re proud you learned (communication, confidence, pacing, etc.)?",
    "{PLAYER}, what’s a moment you felt genuinely desired and it changed your mood for days?",
    "{PLAYER}, what’s the best “recovery” you’ve ever pulled after something went wrong mid-hookup?",
    "{PLAYER}, what’s a thing you’ve tried once and thought, “never again”?",
    "{PLAYER}, what’s a thing you avoided for years and ended up enjoying?",
    "{PLAYER}, what’s a body preference you have that you consider very specific?",
    "{PLAYER}, what’s the most important ingredient for you: lust, comfort, or trust?",
    "{PLAYER}, what kind of explicit talk feels hot to you, and what kind feels cringe?",
    "{PLAYER}, what’s your honest relationship with porn: helpful, harmful, or just entertainment?",
    "{PLAYER}, what’s a porn expectation you had that real life corrected fast?",
    "{PLAYER}, what’s a moment you surprised yourself with how bold you were?",
    "{PLAYER}, what’s the line between “rough fun” and “not okay” for you?",
    "{ALL}, what’s one rule that keeps explicit conversations hot but respectful?"
  ]
},
{
  title: "📐 Anatomy & Preferences 📐",
  items: [
    "{PLAYER}, do you have a clear preference when it comes to size, or is it secondary for you?",
    "{PLAYER}, when you think about bodies, what proportion feels most appealing to you?",
    "{PLAYER}, do you notice shape before size, or size before shape?",
    "{PLAYER}, do you personally prefer cut, uncut, or does it genuinely not matter to you?",
    "{PLAYER}, what about that preference matters to you: look, feel, or familiarity?",
    "{PLAYER}, is symmetry something you consciously notice on a body?",
    "{PLAYER}, do you tend to prefer bodies that look athletic, average, or soft?",
    "{PLAYER}, what physical feature do you think you’re more selective about than most people?",
    "{PLAYER}, do you care more about how a body looks or how it moves?",
    "{PLAYER}, is body hair something you have a preference about, or are you flexible?",
    "{PLAYER}, do you notice posture as part of physical attraction?",
    "{PLAYER}, do you have a preference regarding height differences?",
    "{PLAYER}, do proportions matter more to you than individual features?",
    "{PLAYER}, what’s a physical trait you didn’t think you cared about until you did?",
    "{PLAYER}, do you tend to like familiar body types or ones different from your own?",
    "{PLAYER}, is there a physical detail you always notice first, even unintentionally?",
    "{PLAYER}, do you feel your preferences have changed over time?",
    "{PLAYER}, is confidence able to override physical preferences for you?",
    "{PLAYER}, do you think your preferences are very specific or fairly broad?",
    "{PLAYER}, do you usually know quickly if someone fits your physical taste?",
    "{PLAYER}, do you consider your own body type when thinking about preferences?",
    "{PLAYER}, do you think porn influenced your preferences, even slightly?",
    "{PLAYER}, is there a preference you have that surprises people when you say it out loud?",
    "{PLAYER}, are there physical traits you appreciate more in real life than on screen?",
    "{PLAYER}, do you separate physical attraction from emotional attraction easily?",
    "{PLAYER}, do you think preferences are fixed or shaped by experience?",
    "{PLAYER}, is there a physical feature you used to dislike but grew to appreciate?",
    "{PLAYER}, do you care more about overall harmony or standout features?",
    "{PLAYER}, do you feel more attracted to similarity or contrast?",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{PLAYER}, what physical preference of yours feels the most honest?",
    "{ALL}, do you think physical preferences say more about taste or experience?"
  ]
},
{
  title: "⚖️ Roles & Dynamics ⚖️",
  items: [
    "{PLAYER}, how do you usually identify your role: top, bottom, versatile, or fluid?",
    "{PLAYER}, how important is role compatibility for you when attraction is there?",
    "{PLAYER}, do you feel more comfortable sticking to one role or adapting to the situation?",
    "{PLAYER}, has your preferred role changed over time?",
    "{PLAYER}, what made you realize your current role preference?",
    "{PLAYER}, do you tend to communicate your role early or wait and see?",
    "{PLAYER}, how flexible are you when chemistry is strong?",
    "{PLAYER}, what role dynamic makes you feel most relaxed?",
    "{PLAYER}, what role dynamic challenges you in a good way?",
    "{PLAYER}, do you think roles describe you well, or do they oversimplify?",
    "{PLAYER}, how do you feel about switching roles with the same partner?",
    "{PLAYER}, what kind of dynamic helps you feel confident?",
    "{PLAYER}, what role expectation do you find outdated or limiting?",
    "{PLAYER}, do you prefer clear roles or more open-ended dynamics?",
    "{PLAYER}, how do you usually handle role mismatch?",
    "{PLAYER}, what makes role negotiation feel easy to you?",
    "{PLAYER}, what makes role discussion feel awkward?",
    "{PLAYER}, do you think roles are more about preference or circumstance?",
    "{PLAYER}, what kind of partner makes you curious to try a different dynamic?",
    "{PLAYER}, how important is mutual understanding of roles to you?",
    "{PLAYER}, do you associate roles more with physical comfort or mental comfort?",
    "{PLAYER}, what assumption about your role do people often make incorrectly?",
    "{PLAYER}, do you feel pressure to fit a role based on your appearance?",
    "{PLAYER}, how do you feel about role labels in dating apps?",
    "{PLAYER}, what role-related boundary is important for you?",
    "{PLAYER}, do you think roles should be fixed, flexible, or optional?",
    "{PLAYER}, what role dynamic feels most natural to you right now?",
    "{PLAYER}, how do you feel when a partner challenges your usual role?",
    "{PLAYER}, what role conversation do you wish was more normalized?",
    "{PLAYER}, do you see roles as identity, preference, or just logistics?",
    "{ALL}, do you think role labels help communication or create expectations?"
  ]
},
{
  title: "❌ Never Have I Ever – Intimate & Sexual ✔",
  items: [
    "{ALL}, never have I ever felt instant chemistry that surprised me.",
    "{ALL}, never have I ever been more attracted to someone after talking rather than seeing them.",
    "{ALL}, never have I ever misjudged sexual compatibility at first glance.",
    "{ALL}, never have I ever felt nervous right before an intimate moment.",
    "{ALL}, never have I ever had a physical preference I didn’t expect.",
    "{ALL}, never have I ever changed my mind about someone after getting closer.",
    "{ALL}, never have I ever had an awkward moment that turned into a good memory.",
    "{ALL}, never have I ever felt pressure to fit a role that wasn’t really mine.",
    "{ALL}, never have I ever discovered a preference later than most people.",
    "{ALL}, never have I ever felt disappointed even though expectations were high.",
    "{ALL}, never have I ever been pleasantly surprised by chemistry I didn’t plan for.",
    "{ALL}, never have I ever realized attraction wasn’t mutual in the same way.",
    "{ALL}, never have I ever learned something important from a bad experience.",
    "{ALL}, never have I ever had a moment where communication saved the situation.",
    "{ALL}, never have I ever felt more confident after an intimate experience.",
    "{ALL}, never have I ever laughed in the middle of something that was supposed to be serious.",
    "{ALL}, never have I ever felt unsure about my preferences and later clarified them.",
    "{ALL}, never have I ever been attracted to someone outside my usual type.",
    "{ALL}, never have I ever felt relief after setting a clear boundary.",
    "{ALL}, never have I ever had an expectation that reality quickly corrected.",
    "{ALL}, never have I ever felt genuinely chosen rather than just desired.",
    "{ALL}, never have I ever had an intimate moment that boosted my self-esteem.",
    "{ALL}, never have I ever felt awkward about my body and later stopped caring.",
    "{ALL}, never have I ever realized comfort mattered more than excitement.",
    "{ALL}, never have I ever had a small mishap that didn’t actually ruin anything.",
    "{ALL}, never have I ever felt more connected after an honest conversation.",
    "{ALL}, never have I ever wished I had spoken up sooner about a preference.",
    "{ALL}, never have I ever learned more from a disappointment than a success.",
    "{ALL}, never have I ever been surprised by how flexible my tastes could be.",
    "{ALL}, never have I ever felt proud for handling an intimate situation well.",
    "{ALL}, never have I ever noticed my preferences changing with age or experience.",
    "{ALL}, never have I ever felt instant trust with the wrong person.",
    "{ALL}, never have I ever realized attraction doesn’t always mean compatibility.",
    "{ALL}, never have I ever had a moment that reshaped what I want going forward.",
    "{ALL}, never have I ever felt more confident after being honest about what I want.",
    "{ALL}, never have I ever recognized a personal boundary only after crossing it.",
    "{ALL}, never have I ever had an intimate experience that felt unexpectedly wholesome.",
    "{ALL}, never have I ever felt gratitude for a situation that didn’t work out.",
    "{PLAYER}, Wild Card!  Pick one other player and ask them a direct and personal question of your own creation.",
    "{PLAYER}, Wild Card!  Ask a single, spontaneous question to all other players. Everyone must answer.",
    "{PLAYER}, Wild Card!  Give one other player a Dare that can be easily performed right now.",
    "{ALL}, never have I ever been surprised by my own openness.",
    "{ALL}, never have I ever realized that communication was the real turning point."
  ]
},
{
  title: "🕯️ Bodies, Minds & Early Memories 🕯️",
  items: [
    "{PLAYER}, do you remember the first time you realized you were attracted to another boy?",
    "{PLAYER}, what physical detail first caught your attention when you were younger, even before you understood why?",
    "{PLAYER}, what part of your body were you most aware of growing up?",
    "{PLAYER}, what confused you the most about desire when you were a teenager?",
    "{PLAYER}, was there a moment when you realized your thoughts about men were different from what you were told they should be?",
    "{PLAYER}, what memory of early attraction still feels vivid in your body, not just your mind?",
    "{PLAYER}, what was the first fantasy you remember having that made you stop and think?",
    "{PLAYER}, what feeling came first for you growing up: curiosity, excitement, or confusion?",
    "{PLAYER}, was there a moment you realized your body was reacting before your mind caught up?",
    "{PLAYER}, what did you misunderstand the most about sex when you were younger?",
    "{PLAYER}, what’s something you worried about your body that later turned out not to matter?",
    "{PLAYER}, what part of male bodies fascinated you early on, even if you didn’t name it then?",
    "{PLAYER}, what memory makes you smile now, even if it felt awkward at the time?",
    "{PLAYER}, what’s something you believed about sex or attraction that reality later corrected?",
    "{PLAYER}, when did attraction start feeling less abstract and more physical for you?",
    "{PLAYER}, what was your first adult sexual experience that felt like a real step forward?",
    "{PLAYER}, what surprised you the most about real bodies compared to imagination?",
    "{PLAYER}, what was your first sexual experience that felt genuinely satisfying?",
    "{PLAYER}, what’s a physical preference you didn’t have at first but developed over time?",
    "{PLAYER}, what’s something you enjoy now that younger-you would have been shocked by?",
    "{PLAYER}, what’s a sexual memory that stands out more for the emotion than the act?",
    "{PLAYER}, what’s the most awkward adult sexual moment you can laugh about now?",
    "{PLAYER}, what’s a small physical “failure” that didn’t ruin the experience?",
    "{PLAYER}, what’s a moment where your confidence surprised even you?",
    "{PLAYER}, what’s something about sex that became better once expectations dropped?",
    "{PLAYER}, what’s a conquest that mattered more for what it proved to you internally?",
    "{PLAYER}, what’s a sexual disappointment that helped refine what you actually want?",
    "{PLAYER}, what’s something physical you appreciate much more now than in your twenties?",
    "{PLAYER}, what’s a sensation you associate strongly with good sex?",
    "{PLAYER}, what’s the biggest difference between how you imagined sex and how you experience it now?",
    "{PLAYER}, what’s a sexual moment that made you feel very present in your body?",
    "{PLAYER}, what’s a preference you once thought was “wrong” and now fully accept?",
    "{PLAYER}, what’s something about male intimacy you find more beautiful than expected?",
    "{PLAYER}, what’s a memory where body and mind finally felt aligned?",
    "{PLAYER}, what’s a sexual experience that quietly boosted your self-esteem?",
    "{PLAYER}, what’s something you learned about yourself through physical intimacy?",
    "{PLAYER}, what’s a detail about bodies that has become more important with age?",
    "{PLAYER}, what’s a sexual habit or taste that matured with you?",
    "{PLAYER}, what’s one memory—physical or emotional—that shaped how you experience intimacy today?",
    "{ALL}, do you think desire starts more in the body or in the mind?"
  ]
},
{
  title: "🌿 Nudism & Naturism – Experiences & Mindset 🌿",
  items: [
    "{PLAYER}, do you remember your first time being nude around other people?",
    "{PLAYER}, what feeling came first during your first nudist experience: freedom, fear, or curiosity?",
    "{PLAYER}, what was the biggest mental hurdle before getting naked in front of others?",
    "{PLAYER}, what surprised you the most the first time you were in a nudist space?",
    "{PLAYER}, what part of your body made you the most self-conscious at first?",
    "{PLAYER}, how long did it take for nudity to start feeling normal to you?",
    "{PLAYER}, what was your first thought once everyone was already naked?",
    "{PLAYER}, what fear about nudism turned out to be completely unfounded?",
    "{PLAYER}, what’s the most awkward moment you’ve had while nude in a non-sexual setting?",
    "{PLAYER}, what’s the funniest thing that ever happened to you in a nudist environment?",
    "{PLAYER}, what made you realize nudism wasn’t about sex at all?",
    "{PLAYER}, what was your first positive surprise about being nude with others?",
    "{PLAYER}, what situation felt more intimidating nude than you expected?",
    "{PLAYER}, what made you relax and forget about your body completely?",
    "{PLAYER}, what’s a moment where you felt genuinely proud of your body while nude?",
    "{PLAYER}, what part of nudism feels the most freeing to you now?",
    "{PLAYER}, how did your perception of other people’s bodies change after nudism?",
    "{PLAYER}, what insecurity lost power once you experienced social nudity?",
    "{PLAYER}, what’s something about nudist spaces that outsiders often misunderstand?",
    "{PLAYER}, how do you usually explain nudism to someone who doesn’t get it?",
    "{PLAYER}, what’s the most common reaction you get when people find out you’re a nudist?",
    "{PLAYER}, what kind of question from non-nudists annoys you the most?",
    "{PLAYER}, what kind of curiosity from non-nudists feels respectful?",
    "{PLAYER}, what’s the biggest difference between locker-room nudity and nudism for you?",
    "{PLAYER}, how did your first locker-room experiences shape your relationship with nudity?",
    "{PLAYER}, what’s something that felt very different nude in a locker room compared to other spaces?",
    "{PLAYER}, what moment made you stop comparing your body to others?",
    "{PLAYER}, what part of nudism helped you accept aging or body changes?",
    "{PLAYER}, what’s a small rule or unspoken code you learned in nudist environments?",
    "{PLAYER}, what behavior instantly makes a nudist space feel unsafe or uncomfortable?",
    "{PLAYER}, what makes a nudist environment feel respectful and calm?",
    "{PLAYER}, what’s a mistake you made early on as a nudist that you learned from?",
    "{PLAYER}, what’s a moment where nudism helped your confidence outside nudist spaces?",
    "{PLAYER}, what’s the hardest thing to explain to people who see nudity as automatically sexual?",
    "{PLAYER}, what’s something you personally gained from nudism beyond body acceptance?",
    "{PLAYER}, what’s the biggest difference between your first nudist experience and your most recent one?",
    "{PLAYER}, what advice would you give to someone nervous about their first nudist experience?",
    "{PLAYER}, what’s a nudist experience that changed how you see yourself?",
    "{PLAYER}, what part of nudism still challenges you, even now?",
    "{ALL}, what do you think nudism teaches people that clothes usually hide?"
  ]
}
];

if (Array.isArray(window.QUESTION_DATA)) {
  window.QUESTION_DATA.forEach((category) => {
    if (category && typeof category === 'object') {
      Object.freeze(category.items);
      Object.freeze(category);
    }
  });
  Object.freeze(window.QUESTION_DATA);
}
